/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "list.h"

int *
add_list_1_svc(node *argp, struct svc_req *rqstp)
{
	static int  result;
	result = 0;
	node* temp;
	temp = argp;
	printf("Numbers are: { ");
	while( temp!=NULL ){
		result += temp->x;
		printf("%d, ",temp->x);	
		temp = temp->next;
	}
	printf("}\n");

	return &result;
}
