/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "list.h"

node  *head;

node* mknode(int x){
	if( head == NULL ){
		head = (node*)malloc(sizeof(node));
		head->x = x;
		head->next = NULL;
	}else{
		node* temp = head;
		while( temp->next!=NULL )	temp = temp->next;
		temp->next = (node*)malloc(sizeof(node));
		temp->next->x = x;
		temp->next->next = NULL;
	}
	return head;
}

void
list_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;

	head = mknode(1);
	head = mknode(2);
	head = mknode(102);
	head = mknode(40);

#ifndef	DEBUG
	clnt = clnt_create (host, LIST, LIST_OP, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = add_list_1(head, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Sum is : %d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	list_1 (host);
exit (0);
}
