/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


void
nfs_arya_1(char *host)
{
	CLIENT *clnt;
	bufnode  *result_1;
	bufnode  nfs_ls_1_arg;
	int  *result_2;
	file_args_w  nfs_write_1_arg;
	bufnode  *result_3;
	file_args_r  nfs_read_1_arg;
	int  *result_4;
	bufnode  nfs_cd_1_arg;
	bufnode  *result_5;
	bufnode  getattr_1_arg;
	int  *result_6;
	bufnode  setattr_1_arg;
	int  *result_7;
	bufnode  nfs_remove_1_arg;
	int  *result_8;
	bufnode  nfs_mkdir_1_arg;
	int  *result_9;
	bufnode  nfs_touch_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, nfs_arya, nfs, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = nfs_ls_1(&nfs_ls_1_arg, clnt);
	if (result_1 == (bufnode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = nfs_write_1(&nfs_write_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = nfs_read_1(&nfs_read_1_arg, clnt);
	if (result_3 == (bufnode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = nfs_cd_1(&nfs_cd_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = getattr_1(&getattr_1_arg, clnt);
	if (result_5 == (bufnode *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = setattr_1(&setattr_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = nfs_remove_1(&nfs_remove_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = nfs_mkdir_1(&nfs_mkdir_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = nfs_touch_1(&nfs_touch_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nfs_arya_1 (host);
exit (0);
}
