/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"

bufnode *
nfs_ls_1_svc(bufnode *argp, struct svc_req *rqstp)
{
	static bufnode  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nfs_write_1_svc(file_args_w *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bufnode *
nfs_read_1_svc(file_args_r *argp, struct svc_req *rqstp)
{
	static bufnode  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nfs_cd_1_svc(bufnode *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bufnode *
getattr_1_svc(bufnode *argp, struct svc_req *rqstp)
{
	static bufnode  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
setattr_1_svc(bufnode *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nfs_remove_1_svc(bufnode *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nfs_mkdir_1_svc(bufnode *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
nfs_touch_1_svc(bufnode *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
